version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    image: unclelyozha/replyozha:skolobot1.0
    env_file:
      - .prod.env
    environment:
      - NODE_ENV=prod
